[program:api_embed]
command=/home/pi/api_embed_env/bin/uvicorn app.main:app --host 0.0.0.0 --port 6959 --workers 2
directory=/home/pi/.services/api_embed
user=pi
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/home/pi/.services/api_embed/logs/api_embed.err.log
stdout_logfile=/home/pi/.services/api_embed/logs/api_embed.out.log
